name: 'Attention: Ruby'
favicon: null
layout_spectrum: 0.49121
typography_spectrum: 1
title: 'Attention: Ruby'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9827335015870631
  lightness: 0.25
  saturation: 0.625
  rhythmicContrast: 0.7049042843282223
purpose: []
